import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/utils/app_error.dart';
import '../../../core/utils/result.dart';
import '../../auth/providers/auth_provider.dart';
import '../domain/models/alert_preference_model.dart';
import 'alert_center_provider.dart';

// ─── Alert Preferences Notifier ───────────────────────────────────────────────

/// AsyncNotifier managing the global alert preferences with CRUD mutations.
///
/// Loads the global preferences for the current user on build.
/// Provides validated methods to update preferences (master toggle, thresholds,
/// per-category enable/disable, predictions toggle, quiet hours).
///
/// Methods that can fail with validation errors return [Result<void, AppError>].
class AlertPreferencesNotifier extends AsyncNotifier<AlertPreferenceModel> {
  @override
  Future<AlertPreferenceModel> build() async {
    final user = ref.watch(userProvider);
    if (user == null) {
      return AlertPreferenceModel.defaults('');
    }

    final repo = ref.watch(alertPreferencesRepositoryProvider);
    final result = await repo.getGlobalPreferences(user.id);

    switch (result) {
      case Success(:final value):
        return value;
      case Failure():
        // If not found, initialize defaults and return them.
        await repo.initializeDefaults(user.id);
        return AlertPreferenceModel.defaults(user.id);
    }
  }

  // ---------------------------------------------------------------------------
  // Threshold Validation & Update
  // ---------------------------------------------------------------------------

  /// Validates that all threshold values are multiples of 5 between 10 and 100.
  ///
  /// Valid values: {10, 15, 20, 25, ..., 95, 100}.
  /// Returns a [ValidationError] if any value is invalid, otherwise null.
  static AppError? validateThresholds(List<int> thresholds) {
    for (final value in thresholds) {
      if (value < 10 || value > 100 || value % 5 != 0) {
        return AppError.validation(
          'Invalid threshold value: $value. '
          'Must be a multiple of 5 between 10 and 100 inclusive.',
        );
      }
    }
    return null;
  }

  /// Updates the configured thresholds after validation.
  ///
  /// Each value must be in {10, 15, 20, 25, ..., 95, 100}.
  /// If any value is invalid, the entire update is rejected and a
  /// [ValidationError] is returned.
  Future<Result<void, AppError>> updateThresholds(
    List<int> thresholds,
  ) async {
    final validationError = validateThresholds(thresholds);
    if (validationError != null) {
      return Failure(validationError);
    }

    final current = state.valueOrNull;
    if (current == null) {
      return Failure(AppError.validation('Preferences not loaded yet.'));
    }

    final updated = current.copyWith(thresholds: thresholds);
    return _savePreferences(updated);
  }

  // ---------------------------------------------------------------------------
  // Master Toggle
  // ---------------------------------------------------------------------------

  /// Enables or disables all budget alerts via the master toggle.
  ///
  /// When disabled ([enabled] = false), no alerts or notifications are
  /// generated by the Alert Engine or Prediction Engine.
  Future<Result<void, AppError>> toggleMasterSwitch(bool enabled) async {
    final current = state.valueOrNull;
    if (current == null) {
      return Failure(AppError.validation('Preferences not loaded yet.'));
    }

    final updated = current.copyWith(isEnabled: enabled);
    return _savePreferences(updated);
  }

  // ---------------------------------------------------------------------------
  // Per-Category Enable/Disable
  // ---------------------------------------------------------------------------

  /// Enables or disables alerts for a specific category.
  ///
  /// Creates a category-specific preference record if one doesn't exist,
  /// inheriting settings from the global preferences.
  Future<Result<void, AppError>> toggleCategoryAlerts(
    String categoryId,
    bool enabled,
  ) async {
    final user = ref.read(userProvider);
    if (user == null) {
      return Failure(AppError.validation('User not authenticated.'));
    }

    final repository = ref.read(alertPreferencesRepositoryProvider);

    // Check if category-specific preferences already exist.
    final existingResult =
        await repository.getCategoryPreferences(user.id, categoryId);

    AlertPreferenceModel categoryPrefs;
    switch (existingResult) {
      case Success(:final value):
        if (value != null) {
          categoryPrefs = value.copyWith(isEnabled: enabled);
        } else {
          // Create new category preferences inheriting from global.
          final global = state.valueOrNull;
          categoryPrefs = AlertPreferenceModel(
            id: 'pref_${user.id}_$categoryId',
            userId: user.id,
            categoryId: categoryId,
            isEnabled: enabled,
            thresholds: global?.thresholds ?? const [50, 75, 90, 100],
            predictionsEnabled: global?.predictionsEnabled ?? true,
            quietHoursStart: global?.quietHoursStart,
            quietHoursEnd: global?.quietHoursEnd,
          );
        }
      case Failure(:final error):
        return Failure(error);
    }

    final saveResult = await repository.savePreferences(categoryPrefs);
    switch (saveResult) {
      case Success():
        return const Success(null);
      case Failure(:final error):
        return Failure(error);
    }
  }

  // ---------------------------------------------------------------------------
  // Predictions Toggle
  // ---------------------------------------------------------------------------

  /// Enables or disables prediction alerts (separate from threshold alerts).
  Future<Result<void, AppError>> togglePredictions(bool enabled) async {
    final current = state.valueOrNull;
    if (current == null) {
      return Failure(AppError.validation('Preferences not loaded yet.'));
    }

    final updated = current.copyWith(predictionsEnabled: enabled);
    return _savePreferences(updated);
  }

  // ---------------------------------------------------------------------------
  // Quiet Hours Configuration
  // ---------------------------------------------------------------------------

  /// Validates a time string in "HH:mm" format.
  ///
  /// Returns true if the format is valid (00:00 – 23:59).
  static bool isValidTimeFormat(String time) {
    final regex = RegExp(r'^([01]\d|2[0-3]):([0-5]\d)$');
    return regex.hasMatch(time);
  }

  /// Sets quiet hours start and end times.
  ///
  /// Pass null for both to disable quiet hours.
  /// Times must be in "HH:mm" format (e.g., "22:00", "07:00").
  /// Both must be provided together or both must be null.
  Future<Result<void, AppError>> setQuietHours(
    String? start,
    String? end,
  ) async {
    final current = state.valueOrNull;
    if (current == null) {
      return Failure(AppError.validation('Preferences not loaded yet.'));
    }

    // Both must be null (disable) or both must be valid times.
    if ((start == null) != (end == null)) {
      return Failure(
        AppError.validation(
          'Both quiet hours start and end must be provided, '
          'or both must be null to disable quiet hours.',
        ),
      );
    }

    if (start != null && !isValidTimeFormat(start)) {
      return Failure(
        AppError.validation(
          'Invalid quiet hours start format: "$start". Expected "HH:mm".',
        ),
      );
    }

    if (end != null && !isValidTimeFormat(end)) {
      return Failure(
        AppError.validation(
          'Invalid quiet hours end format: "$end". Expected "HH:mm".',
        ),
      );
    }

    final updated = current.copyWith(
      quietHoursStart: () => start,
      quietHoursEnd: () => end,
    );
    return _savePreferences(updated);
  }

  // ---------------------------------------------------------------------------
  // Private Helpers
  // ---------------------------------------------------------------------------

  /// Persists updated preferences and updates local state optimistically.
  Future<Result<void, AppError>> _savePreferences(
    AlertPreferenceModel updated,
  ) async {
    final repo = ref.read(alertPreferencesRepositoryProvider);
    final result = await repo.savePreferences(updated);
    switch (result) {
      case Success():
        state = AsyncData(updated);
        return const Success(null);
      case Failure(:final error):
        return Failure(error);
    }
  }
}

/// Provider for the alert preferences notifier.
final alertPreferencesProvider =
    AsyncNotifierProvider<AlertPreferencesNotifier, AlertPreferenceModel>(
  AlertPreferencesNotifier.new,
);
